### ISSUE TITLE
extract feature and usage example.

### ISSUE THREAD

**Issue by mbusb** [barneygale/iso9660#3]
There is no usage example to extract iso content and no example to use it as module/ library. It would be awesome if you support this feature. This can br some thing like this "python iso9660.py [path] [extract_dir_path]".
Thanks in advance

**Comment by BharathChandraKS** [comment]
Could someone please provide an example on how to extract the ISO files using this code. I am also facing the same issue. 

(env) -bash-4.1$ python iso9660.py /var/www/iso/iso9660-master/VMware-VMvisor-Installer-6.8.2-15944714.x86_64.iso /var/www/iso/iso9660-master/ISO/
Traceback (most recent call last):
  File "iso9660.py", line 317, in <module>
    sys.stdout.write(cd.get_file(ret_path))
  File "iso9660.py", line 111, in get_file
    parent_dir = self._dir_record_by_root(path)
  File "iso9660.py", line 158, in _dir_record_by_root
    current = self._search_dir_children(current, remaining[0])
  File "iso9660.py", line 264, in _search_dir_children
    raise ISO9660IOError(term)
__main__.ISO9660IOError: Path not found: VAR

**Comment by BharathChandraKS** [comment]
(env) -bash-4.1$ python iso9660.py /var/www/iso/iso9660-master/Image.iso /var/www/iso/iso9660-master/ISO/
Traceback (most recent call last):
  File "iso9660.py", line 317, in <module>
    sys.stdout.write(cd.get_file(ret_path))
  File "iso9660.py", line 111, in get_file
    parent_dir = self._dir_record_by_root(path)
  File "iso9660.py", line 158, in _dir_record_by_root
    current = self._search_dir_children(current, remaining[0])
  File "iso9660.py", line 264, in _search_dir_children
    raise ISO9660IOError(term)
__main__.ISO9660IOError: Path not found: VAR

**Comment by JeanOlivier** [comment]
See the ISO9660 class in this link for a working example: https://sourceforge.net/p/dcisotools/code/ci/master/tree/gditools.py
